[package]
name = "common"
version = "0.1.0"
edition = "2021"


[lib]
name = "common"
path = "src/lib.rs"

[dependencies]
axum = "0.7.5"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
validator = { version = "0.18.1", features = ["derive"] }
